### ISSUE TITLE
parallelize multi task script

### ISSUE THREAD

**Issue by staabm** [veewee/composer-run-parallel#11]
|    Q        |   A
|------------ | -----
| Version     | latest

### Support Question

I wonder whether its possible to run run tasks in parallel if they are notated like

```
        "phpstan": [
            "vendor/bin/phpstan analyse -c app/homie/phpstan.neon.dist",
            "vendor/bin/phpstan analyse -c app/www/phpstan.neon.dist",
            "vendor/bin/phpstan analyse -c app/whitelabel/phpstan.neon.dist",
            "vendor/bin/phpstan analyse -c app/partner/phpstan.neon.dist",
            "vendor/bin/phpstan analyse -c app/admin/phpstan.neon.dist",
            "vendor/bin/phpstan analyse -c app/api/phpstan.neon.dist",
            "vendor/bin/phpstan analyse -c app/modeo_partner/phpstan.neon.dist",
            "vendor/bin/phpstan analyse -c scripts/phpstan.neon.dist",
            "vendor/bin/phpstan analyse -c lib/plugins/clxMobileNet/phpstan.neon.dist"
        ],
```

I would love to run these tasks 2 commands at a time.
-> thats another question I think: is it possible to define how many tasks are executed in parallel?

**Comment by staabm** [comment]
for now I solved it like

```
        "phpstan-pull-request": [
            "@parallel phpstan-pull-request-1 phpstan-pull-request-2",
            "vendor/bin/phpstan analyse -c scripts/phpstan.neon.dist -vvv",
            "vendor/bin/phpstan analyse -c deploy-phpstan.neon.dist -vvv",
            "vendor/bin/phpstan analyse -c lib/plugins/clxMobileNet/phpstan.neon.dist -vvv",
            "@php vendor/plugins/rocket/.github/ensure-stable-rocket.php --allow-dev-master",
            "@php vendor/plugins/clxMobileNetPortable/.github/ensure-stable-portable.php"
        ],
        "phpstan-pull-request-1": [
            "vendor/bin/phpstan analyse -c app/homie/phpstan.neon.dist -vvv",
            "vendor/bin/phpstan analyse -c app/www/phpstan.neon.dist -vvv",
            "vendor/bin/phpstan analyse -c app/admin/phpstan.neon.dist -vvv"
        ],
        "phpstan-pull-request-2": [
            "vendor/bin/phpstan analyse -c app/whitelabel/phpstan.neon.dist -vvv",
            "vendor/bin/phpstan analyse -c app/partner/phpstan.neon.dist -vvv",
            "vendor/bin/phpstan analyse -c app/api/phpstan.neon.dist -vvv",
            "vendor/bin/phpstan analyse -c app/modeo_partner/phpstan.neon.dist -vvv"
        ],
```

maybe thats even good enough :)..?

**Comment by veewee** [comment]
Hello,

Thanks for reaching out.
Currently, it uses composer's `ProcessExecutor` to schedule async processes which has a maximum of 10 concurrent processes. It is something that could be overwritten at first sight, but I didn't foresee anything to do it configurably from this package.

More info about how it works can be found here:

* https://github.com/composer/composer/blob/da83d29d8ac634783bc70b0f3b7847bae3e081d9/src/Composer/Util/ProcessExecutor.php#L284-L292
* https://github.com/veewee/composer-run-parallel/blob/60f357260cac77f3cad7050eceacebd3fdd907af/src/Scripts/ParallelScript.php#L50-L52


I am organizing my parallel tasks in a similar way as you pasted in your latest comment and I think that is the way to go.
Example from my end:

```json
    "scripts": {
        "cs": "PHP_CS_FIXER_IGNORE_ENV=1 php ./tools/php-cs-fixer.phar fix --dry-run",
        "psalm": "./vendor/bin/psalm --no-cache --stats",
        "tests": "./tools/phpunit.phar --coverage-text --color",
        "coverage": "@php ./tools/full-coverage-check.php .phpunit.cache/clover/clover.xml",
        "infection": [
            "Composer\\Config::disableProcessTimeout",
            "./tools/infection.phar --show-mutations -v"
        ],
        "ci": [
            "@parallel cs psalm tests",
            "@parallel coverage infection"
        ]
    },
```

I'm using `composer run ci` for validating everything. 
It first runs coding standards, phpunit and unit tests
If all is well, it then checks the test coverage and mutation tests.

For me it also makes sense to run these commands in parallel, but in different parallel stages.

**Comment by staabm** [comment]
thanks for the fast reply. really cool stuff - I think it works for me.

thanks again.
