### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by lazka** [veewee/composer-run-parallel#5]
I was wondering if you would consider supporting php 7.3 or would accept a contribution adding support.

Feel free to close this if this is out of scope.

thanks

**Comment by veewee** [comment]
Hello @lazka 

That version won't be supported anymore in 2 months.
Sorry, I am not planning to maintain support for ancient PHP versions.

**Comment by lazka** [comment]
Fair enough, thanks for the response.
