### ISSUE TITLE
PHP 8.3 Support

### ISSUE THREAD

**Issue by acelaya** [veewee/composer-run-parallel#9]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I'm updating some projects to PHP 8.3, and this seems to be the only dependency not supporting it yet.

There's no hurry, as PHP 8.3 is not even stable yet and I'm adding only preliminary support and trying to identify dependencies which do not support it yet.

Would you be willing to support PHP 8.3 on this library? If so, I can provide a pull request.

**Comment by veewee** [comment]
Sounds good, feel free to provide a PR!
